import { DEFAULT_THEME } from '@mantine/core';

export const DEFAULT_ACCOUNT_ICON = 'Wallet';
export const DEFAULT_ACCOUNT_COLOR = '#4C6EF5';
export const ACCOUNT_ICON_SIZE = 24;

const FILLED_SHADE = 6;
const ACCOUNT_FILL_WHITE = '#FFFFFF';
const ACCOUNT_FILL_BLACK = '#000000';
const ACCOUNT_FILL_LIME = DEFAULT_THEME.colors.lime[FILLED_SHADE];
const ACCOUNT_FILL_YELLOW = DEFAULT_THEME.colors.yellow[FILLED_SHADE];
const ACCOUNT_FILL_ORANGE = DEFAULT_THEME.colors.orange[FILLED_SHADE];

export const ACCOUNT_COLORS = [
  ACCOUNT_FILL_WHITE,
  ACCOUNT_FILL_BLACK,
  DEFAULT_THEME.colors.red[FILLED_SHADE],
  DEFAULT_THEME.colors.pink[FILLED_SHADE],
  DEFAULT_THEME.colors.grape[FILLED_SHADE],
  DEFAULT_THEME.colors.violet[FILLED_SHADE],
  DEFAULT_ACCOUNT_COLOR,
  DEFAULT_THEME.colors.blue[FILLED_SHADE],
  DEFAULT_THEME.colors.cyan[FILLED_SHADE],
  DEFAULT_THEME.colors.teal[FILLED_SHADE],
  DEFAULT_THEME.colors.green[FILLED_SHADE],
  ACCOUNT_FILL_LIME,
  ACCOUNT_FILL_YELLOW,
  ACCOUNT_FILL_ORANGE,
] as const;

export const ACCOUNT_DARK_INK_FILLS = [
  ACCOUNT_FILL_WHITE,
  ACCOUNT_FILL_LIME,
  ACCOUNT_FILL_YELLOW,
  ACCOUNT_FILL_ORANGE,
] as const;
